public with sharing class TaskConstants {
    //Status
    public static final string TASK_STATUS_COMPLETED = 'Completed';
    public static final string TASK_STATUS_NOT_REQUIRED = 'Not Required';//Added by Rahul Jog(Thinqloud) 16/05/2023
    public static final string INCOMPLETE_SUBTASK_ERROR = 'Parent Task cannot be completed if related tasks are not yet complete';
    public static final string INTERACTION_RECORD_TYPE = 'Interaction Task';//Added by Priti Chande(14/04/2023)

}